channels: null
clean:
  butterworth:
    high_pass: 0.5
    low_pass: 80
    order: 5
  clipping_value: 500
  new_frequency: 170
  notch:
    freq: 60
    quality: 15
  steps:
  - butterworth
  - notch
  - downsample
  - clip
label:
  chunk_duration: 10
  test:
    artifact: null
    balance: false
  train:
    artifact: null
    balance: false
  val:
    artifact: null
    balance: false
split:
  amount: null
  as_percentage: true
  test: 20
  tol: 0.25
  train: 60
  val: 20
